---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: http-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: hello-world
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: piiv5wkacr.azurecr.io/hello-world-python:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 0.1G
            cpu: 0.1
          limits:
            memory: 0.5G
            cpu: 0.5
        ports:
        - name: http-api
          containerPort: 8080
  selector:
    matchLabels:
      app: hello-world